---
title: "Text Data Homework"
author: Kyleigh Johnson
date: 11/12/24
format: html
editor: visual
---

This is my completion of the text data assignment where I sort classes and create a word cloud.

## Completion of Plot Showing Number of Courses at Different Levels

```{r}
library( tidyverse )
library ( stringr )
library( readr )
```

```{r}
lfsc <- read_lines( "LifeSciencesCurriculum.txt" )
head( lfsc, 25 )
```

```{r}
str_detect( lfsc, "ENVS|ENVZ|LFSC|BNFO") -> idx

lfsc[ idx ]
```

```{r}
pattern <- "^[A-Z]{4} [0-9]{3}.+[0-9] Hour[s]?\\.$"
grepl( pattern, lfsc ) -> idx
titles <- lfsc[ idx ]
titles
```

```{r}
str_split( titles, pattern = "\\.", simplify = TRUE ) -> raw



data.frame( course = raw[,1],
            title = str_trim(raw[,2]),
            hours = str_trim(raw[,3]), "Hours" ) |>
  mutate( hours = str_remove( hours, "Hour") ) |>
  mutate( hours = as.numeric( str_remove( hours, "s") ) ) |>
  mutate( program = str_split( course, " ", simplify = TRUE)[,1]) |>
  mutate( number = as.numeric( str_split( course, " ", simplify = TRUE)[,2]) ) |>
  select( program, number, title, hours ) -> df

df
```

```{r}
library(dplyr)

df %>%
  mutate( level = floor(number / 100) * 100 ) %>% 
  filter( level %in% c( 100, 200, 300, 400 ) ) %>%  
  group_by( program, level ) %>%                   
  summarise( course_count = n(), .groups = 'drop' ) -> df_sum

df_sum


```

```{r}
course_nums <- with(df_sum, tapply(course_count, list(level, program), sum, default = 0))


barplot( course_nums,
        beside = TRUE,
        col = c( "lightblue", "lightgreen", "lightyellow", "lightpink" ),
        ylab = "Number of Courses",
        xlab = "Program",
        legend = rownames( course_nums ),
        cex.names = 0.7,
        main = "Number of Courses at Each Level in Each Program" )

```

## Word Cloud

```{r}
library(wordcloud2)

idx <- grepl( pattern, lfsc )
lfsc[idx] -> titles
titles

```

```{r}
raw <- str_split(titles, pattern="\\.", simplify = TRUE)
dim(raw)
```

```{r}
program <- str_split( raw[,1], pattern=" ", simplify=TRUE)[,1]

code <- str_split( raw[,1], pattern=" ", simplify=TRUE)[,2]
code <- as.numeric( code )
code 
```

```{r}
title <- raw[,2]
title
```

```{r}
str_split( title, " ")
str_split( title, " ", simplify=TRUE)

as.vector( str_split( title, " ", simplify=TRUE) ) -> words

words <- words[ str_length(words) > 0 ]

words <- sort( words )
words

```

```{r}
data.frame( words, count = 1 ) |> 
  mutate( word = factor( words ) ) |> 
  group_by( word ) |>
  summarize( freq = sum( count )) |> 
  arrange( -freq ) -> tdm 

tdm 
```

```{r}
wordcloud2(data = tdm)

```
